parameters:
- name: buildPlugins
  displayName: Build Plugins
  type: boolean
  default: false
- name: useNightly
  displayName: Use Nightly version number
  type: boolean
  default: true

variables:
  defines: 'NIGHTLY=$(Build.BuildNumber)'
  qtVersion: '5.15.2'

name: 'JDP.$(Date:yyyy-MM-dd).$(Rev:r)'
jobs:
- job: Build

  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-18.04'
      macos:
        imageName: 'macOS-11'
        qtVersion: '6.2.2'
      macosx:
        imageName: 'macOS-10.15'
        qtVersion: '5.12.12'
        skipHardPlugins: 'true'
      win64:
        imageName: 'windows-2019'
        qtArch: 'win64_msvc2019_64'
      win32:
        imageName: 'windows-2019'
        qtArch: 'win32_msvc2019'

  pool:
    vmImage: $(imageName)

  steps:
  - bash: |
      echo '##vso[task.setvariable variable=MatrixName]'$(echo $(Agent.JobName) | cut -d' ' -f2)-
      echo "##vso[task.setvariable variable=arch]$(qtArch)"
      if [ ${{ parameters.useNightly }} = True ]; then
        echo "##vso[task.setvariable variable=nightlyDefines]$(defines)"
        echo "##vso[task.setvariable variable=nightlyString]-nightly"
        echo "##vso[task.setvariable variable=buildNumString]$(Build.BuildNumber)"
      else
        echo "##vso[task.setvariable variable=nightlyDefines]"
        echo "##vso[task.setvariable variable=nightlyString]"
        echo "##vso[task.setvariable variable=buildNumString]"
      fi
    condition: and(succeeded(), ne(variables['dontPublish'], 'true'))
    displayName: 'Set matrix env variables'

  - checkout: self

  - template: ci/install-qt.yml
    parameters:
      version: $(qtVersion)

  - pwsh: ci/scripts/build.ps1
    displayName: 'Build qView'

  - bash: |
      wget 'https://sourceforge.net/projects/qt5ct/files/latest/download'
      tar xf download
      cd qt5ct*
      qmake
      sudo make install
      
      echo "##vso[task.setvariable variable=extra_plugins_maybe]'-extra-plugins=styles/libqt5ct-style.so,platformthemes/libqt5ct.so'"
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: Get qt5ct style (Linux only)

  - pwsh: |
      if ($IsWindows) {
        Invoke-Expression "& 'ci/scripts/windeployqt.ps1' $(buildNumString)"
      } elseif ($IsMacOS) {
        bash ci/scripts/macdeploy.sh $(buildNumString)
      } else {
        bash ci/scripts/linuxdeployqt.sh $(buildNumString) $(extra_plugins_maybe)
      }
    displayName: 'Run deployment script'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'bin'
      artifactName: 'qView$(nightlyString)-$(MatrixName)$(buildNumString)'
    condition: and(succeeded(), ne(variables['dontPublish'], 'true'))
    displayName: 'Publish build artifact'

